### ISSUE TITLE
Incorrect code on your tutorial page

### ISSUE THREAD

**Issue by gerricchaplin** [mackenziechild/raddit#4]
Hi,
Thanks for the great tutorials. I have just been having a look through the first week tutorial. I noticed a little issue where your create method did not match your code.

http://mackenziechild.me/12-in-12/1/
def create
@link = current_user.build(link_params)
should match your code:
def create
@link = current_user.links.build(link_params)

Tutorial is great otherwise!
Thanks for that!

**Comment by mackenziechild** [comment]
Fixed.. Thanks :+1:
