### ISSUE TITLE
Week01: Reddit Clone text tutorial issue

### ISSUE THREAD

**Issue by isjia** [mackenziechild/raddit#6]
## Voting Part

as you mentioned:

> For this we are going to use a handy little gem called **acts_as_votable**. 

so after:

> $ git checkout -b add_acts_as_votable

we need to add `gem 'acts_as_votable', '~> 0.10.0'` before running `bundle install`

and then: 

> $ bundle install

**Comment by mackenziechild** [comment]
Good eye ;) Thanks!
